### PR TITLE
Add tax_code as a accepted field to NetSuite::Records::ExpenseReportExpense

### PR DESCRIPTION
**Pull request by ryandhaase**
This will allow us to send tax code along with expenses that are on expense reports

@ahuth @shirish-pampoorickal

### CODE REVIEW

**Review by shirish-pampoorickal — APPROVED** [review]
I would suggest adding a spec for this change. Otherwise LGTM

**Comment by ryandhaase** [comment]
@shirish-pampoorickal 

@ccmeyers and I made some changes and added specs based on your recommendation.  LGTY?

**Review by ahuth — APPROVED** [review]

**Comment by ahuth** [comment]
Looks good

**Comment by shirish-pampoorickal** [comment]
Thanks for adding the specs. LGTM!

**Pull request merged**
